In [1]:
import numpy as np

In [20]:
N=15
K=4

p_array = np.random.uniform(0,1,N)

print(np.sum(p_array)/N)

T = 100

Participation_info      = np.empty((T,N))


for i in range(N):
    p_tmp = p_array[i]
    tmp = np.random.binomial(1, p_tmp, T)
    
    Participation_info[:,i] = tmp
#     if i==0:
#         print(p_tmp)
#         print(np.sum(tmp))

print(np.sum(Participation_info,axis=1))

0.4784040329885527
[ 7.  7.  7.  8.  6.  6.  6.  8.  5.  8.  8.  7.  8.  7.  6.  5.  8.  7.
  6.  7.  6.  9. 10.  8.  9. 10. 10.  8.  7.  6.  4. 11.  7.  8.  7.  7.
  7.  8.  8.  5.  7.  5.  8.  9.  7.  5.  7.  7.  6.  7.  5.  7.  8.  7.
  9.  6.  8.  7.  6.  8.  8.  6.  6.  6.  5. 10.  7.  8.  7.  5.  8.  6.
  5. 10.  6.  6.  7.  9.  5.  6.  4.  4.  7.  6.  8.  6.  5.  6.  6.  6.
  6.  7.  7.  7.  6.  6.  6.  7.  8.  9.]


In [82]:


Selection_info_random   = np.zeros((T,N))
Selection_info_proposed = np.zeros((T,N))

alpha = 1

for t in range(T):
    
    N_participate_tmp = np.sum(Participation_info[t,:]).astype(int)
    
#     print('[iter=',t,'], N_part=',N_participate_tmp)
#     print()
    
    result_tmp = np.where(Participation_info[t,:] == 1)
    result_tmp = np.reshape(result_tmp,N_participate_tmp)
    
    select_index = np.random.choice(N_participate_tmp, K, replace=False).astype(int)
    select_tmp = result_tmp[select_index]
    
#     print(result_tmp)
#     print(select_tmp)
    
    for j in select_tmp:
        Selection_info_random[t,j] = 1
        
    if t==0:
        Selection_info_proposed[t,:] = Selection_info_random[t,:]
    else:
        Score_coverage = np.sum(Selection_info_proposed,axis=0)
#         print('    [Prop] score_coverage =',Score_coverage)
        
        Score_ovelap = np.zeros(N)
        for i in range(t):
            Score_ovelap = Score_ovelap + Selection_info_proposed[i,:]/(t-i)
#         print('    [Prop] Score_ovelap   =',Score_ovelap)
        
        Score_total = Score_coverage + Score_ovelap + (1-Participation_info[t,:])*1000
#         print('    [Prop] Total_ovelap   =',Score_total)
        
        argsort_tmp = np.argsort(Score_total)
        
        for j in range(K):
            Selection_info_proposed[t,argsort_tmp[j]] = 1
#     print()
    
    
# print()
# print('######################################################')
# print('check the random selection: all value should be K=',K)
# print(np.sum(Selection_info_proposed,axis=1))
# print(np.sum(Selection_info_random,axis=1))
# print()
print('######################################################')
print('Check Coverage Performance ')
print('- Particiaption number')
print(np.sum(Participation_info,axis=0))
print()

print('- Random')
coverage_random = np.sum(Selection_info_random,axis=0)
print(coverage_random)
print(np.min(coverage_random))
print()
print('- Proposed')
coverage_prop = np.sum(Selection_info_proposed,axis=0)
print(coverage_prop)
print(np.min(coverage_prop))

print()
print('######################################################')
print('Check Overlap Performance ')

overlap_performance = np.zeros((T))
selection_info_test = Selection_info_random
for t in range(T):
    if t==0:
        overlap_performance[t] = 0
    else:
        for i in range(t):
            tmp_overlap = selection_info_test[i,:] * selection_info_test[t,:]
            overlap_performance[t] = overlap_performance[t] + np.sum(tmp_overlap)/(t-i)
print('- Random')
print(np.max(overlap_performance))

overlap_performance = np.zeros((T))
selection_info_test = Selection_info_proposed
for t in range(T):
    if t==0:
        overlap_performance[t] = 0
    else:
        for i in range(t):
            tmp_overlap = selection_info_test[i,:] * selection_info_test[t,:]
#             print(np.sum(tmp_overlap))
            overlap_performance[t] = overlap_performance[t] + np.sum(tmp_overlap)/(t-i)
print('- Proposed')            
print(np.max(overlap_performance))
#     if t == 0:
#         selection_tmp = np.

######################################################
Check Coverage Performance 
- Particiaption number
[32. 58. 32.  9. 36. 15. 96. 99. 26. 30. 88. 57.  8. 42. 66.]

- Random
[18. 28. 17.  6. 20.  8. 65. 54. 12. 19. 51. 32.  5. 24. 41.]
5.0

- Proposed
[28. 33. 27.  9. 31. 15. 34. 33. 22. 29. 33. 33.  8. 32. 33.]
8.0

######################################################
Check Overlap Performance 
- Random
10.72249921134642
0.0
2.0
0.0
1.0
1.0
0.0
1.0
2.0
0.0
0.0
2.0
2.0
2.0
1.0
0.0
0.0
2.0
1.0
1.0
2.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
2.0
0.0
3.0
0.0
0.0
2.0
1.0
1.0
1.0
0.0
1.0
2.0
0.0
0.0
1.0
2.0
1.0
0.0
3.0
0.0
1.0
3.0
1.0
2.0
0.0
0.0
0.0
2.0
0.0
2.0
1.0
1.0
1.0
0.0
1.0
1.0
2.0
1.0
1.0
1.0
2.0
0.0
1.0
1.0
2.0
1.0
3.0
1.0
1.0
0.0
2.0
0.0
1.0
2.0
1.0
0.0
2.0
1.0
1.0
2.0
0.0
1.0
1.0
2.0
2.0
2.0
0.0
1.0
3.0
1.0
1.0
2.0
0.0
1.0
1.0
2.0
0.0
3.0
1.0
2.0
0.0
1.0
3.0
0.0
2.0
2.0
0.0
0.0
1.0
1.0
1.0
3.0
0.0
1.0
1.0
2.0
0.0
1.0
1.0
2.0
1.0
3.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
3.0
1.0
1.0
1.0
2.0


2.0
1.0
1.0
1.0
1.0
2.0
0.0
2.0
1.0
0.0
2.0
2.0
1.0
1.0
3.0
0.0
1.0
2.0
1.0
1.0
1.0
2.0
2.0
2.0
1.0
0.0
2.0
1.0
1.0
2.0
1.0
0.0
2.0
1.0
2.0
1.0
2.0
0.0
1.0
2.0
1.0
1.0
3.0
1.0
1.0
1.0
3.0
0.0
3.0
2.0
1.0
0.0
2.0
0.0
2.0
1.0
0.0
1.0
1.0
2.0
0.0
1.0
2.0
1.0
2.0
0.0
2.0
2.0
1.0
1.0
2.0
1.0
1.0
2.0
0.0
3.0
0.0
1.0
0.0
3.0
0.0
0.0
3.0
0.0
2.0
1.0
1.0
2.0
0.0
1.0
2.0
2.0
1.0
2.0
1.0
1.0
3.0
0.0
2.0
1.0
2.0
1.0
1.0
3.0
0.0
2.0
2.0
0.0
1.0
1.0
1.0
1.0
2.0
2.0
2.0
1.0
3.0
0.0
1.0
2.0
1.0
1.0
2.0
1.0
1.0
2.0
1.0
0.0
2.0
2.0
1.0
2.0
1.0
1.0
2.0
0.0
1.0
0.0
2.0
2.0
0.0
2.0
1.0
1.0
3.0
1.0
2.0
1.0
2.0
2.0
1.0
1.0
0.0
2.0
1.0
2.0
1.0
0.0
2.0
2.0
0.0
1.0
2.0
1.0
2.0
2.0
0.0
2.0
1.0
1.0
1.0
2.0
2.0
0.0
2.0
1.0
1.0
2.0
2.0
0.0
1.0
0.0
1.0
2.0
2.0
1.0
1.0
1.0
1.0
1.0
2.0
1.0
2.0
0.0
2.0
0.0
1.0
0.0
1.0
2.0
0.0
2.0
0.0
0.0
1.0
2.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
1.0
1.0
0.0
2.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
2.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
2.0
0.0
2.0
1.0
1.0


In [80]:
print('######################################################')
print('participate probability')
print(p_array)

######################################################
participate probability
[0.36143704 0.63644441 0.32273541 0.13812395 0.34307282 0.18023283
 0.9666326  0.97454148 0.25393089 0.38749817 0.79539458 0.60438571
 0.09581553 0.41792954 0.69788552]
